# adapted from https://flareapp.io/blog/30-how-we-use-elasticsearch-kibana-and-filebeat-to-handle-our-logs

filebeat:
  inputs:
  - enabled: true
    json.add_error_key: true
    json.expand_keys: true
    json.keys_under_root: true
    json.overwrite_keys: true
    paths:
    - /log_data/*.log
    type: log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

setup.template.settings:
  index.number_of_shards: 1

output:
  elasticsearch:
    hosts:
    - http://es-container:9200

processors:
  - drop_fields:
      fields: []